changelog:
  categories:
    - title: 'ğŸš€ New Features'
      labels:
        - 'type::rocket:'
    - title: 'ğŸ Bug Fixes'
      labels:
        - 'type::bug:'
    - title: 'â¬†ï¸ Dependency Updates'
      labels:
        - 'type:dependencies'
    - title: 'ğŸ“– Documentation improvements'
      labels:
        - 'type::memo:'
    - title: 'â›”ï¸ Security'
      labels:
        - 'type:security'
    - title: 'ğŸ‘» Internal changes'
      labels:
        - 'type:internal'